# --- Qatten specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "qatten_learner"
double_q: True
mixer: "qatten"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
n_head: 4
attend_reg_coef: 0.001
state_bias: True
mask_dead: False
weighted_head: False
nonlinear: False

name: "qatten"
