env: pushbox
env_args:
  input_rows: 6
  input_cols: 8
  map_name: "origin"
  episode_limit: 30
  path: Null


learner_log_interval: 1000
log_interval: 1000
runner_log_interval: 1000
t_max: 105000
test_interval: 1000
test_nepisode: 30
test_greedy: True
demo_interval: 1000

save_model: False
use_tensorboard: True
save_model_interval: 20000
